<a href="https://colab.research.google.com/github/EvilMorty13/Python-Learning-BS/blob/main/Chapter_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

In [2]:
import numpy as np

a = [1,2,3,4,5]
print(a)

a_np = np.array([1,2,3,4,5])
type(a_np)

a_np = a_np + 1

print(a_np)
# Really fast


array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

array_2d[0]=array_2d[0]+1;
print(array_2d)

array_2d.shape



[1, 2, 3, 4, 5]
[2 3 4 5 6]
[[2 3 4]
 [4 5 6]
 [7 8 9]]


(3, 3)

##Arrays Data Type

In [12]:
import numpy as np

a_num = np.array([1,2,3,4,5])
a_num.dtype

array_2d = np.array([[1, 2, 3],
                     [4, "5", 6],
                     [7, 8, 9]],dtype=np.float32)

print(array_2d)



[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


##NumPy Array Creation Methods

In [13]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [15]:
ones = np.ones((4,4))
zeros = np.zeros((4,4))

ones = ones*6
print(ones)


[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [17]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
np.linspace(10,100,40)

array([ 10.        ,  12.30769231,  14.61538462,  16.92307692,
        19.23076923,  21.53846154,  23.84615385,  26.15384615,
        28.46153846,  30.76923077,  33.07692308,  35.38461538,
        37.69230769,  40.        ,  42.30769231,  44.61538462,
        46.92307692,  49.23076923,  51.53846154,  53.84615385,
        56.15384615,  58.46153846,  60.76923077,  63.07692308,
        65.38461538,  67.69230769,  70.        ,  72.30769231,
        74.61538462,  76.92307692,  79.23076923,  81.53846154,
        83.84615385,  86.15384615,  88.46153846,  90.76923077,
        93.07692308,  95.38461538,  97.69230769, 100.        ])

##Operations with Arrays

In [21]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

a1 = np.array(l1)
a2 = np.array(l2)


array([ 7,  9, 11, 13, 15])

In [22]:
(a1+a2)*5

array([35, 45, 55, 65, 75])

In [23]:
a3 = np.array([1,2,3])
a4 = np.array([[1],[2]])

a3+a4

array([[2, 3, 4],
       [3, 4, 5]])

In [24]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([1,2,3])

A+B


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

##Slicing NumPy Arrays

In [27]:
exam_scores = np.array([90,85,77,92])
print("First student's score is :",exam_scores[0])


First student's score is : 90


In [28]:
sales_data = np.array([
    [200,300,400],
    [500,600,700],
    [800,100,200]
])

sales_data[0][1]

300

In [36]:
monthly_revenue = np.array([200,110,300,4005,33,44,22,143,134,34,532,34])
monthly_revenue[0:4]

array([ 200,  110,  300, 4005])

In [37]:
monthly_revenue[::2]

array([200, 300,  33,  22, 134, 532])

In [38]:
avg = np.mean(monthly_revenue)
avg

465.9166666666667

In [39]:
monthly_revenue[monthly_revenue>avg]

array([4005,  532])

##ExerciseProject 10.1 Slicing and Indexing with NumPy

In [50]:
monthly_sales = np.array([200,220,250,275,300,320,350,370,400,420,450,475])

print("Sales in January :",monthly_sales[0])
print("Sales in December :",monthly_sales[-1])

quaterly_sales = ([np.sum(monthly_sales[0:3]),np.sum(monthly_sales[3:6]),np.sum(monthly_sales[6:9]),np.sum(monthly_sales[9:12])])

print(quaterly_sales)

monthly_sales[3]=280
print(monthly_sales)

summer = monthly_sales[5:8]
print(summer)
avg_summer = np.mean(summer)
print(avg_summer)

above_avg_month = monthly_sales[monthly_sales>np.mean(monthly_sales)]
print(above_avg_month)


Sales in January : 200
Sales in December : 475
[670, 895, 1120, 1345]
[200 220 250 280 300 320 350 370 400 420 450 475]
[320 350 370]
346.6666666666667
[350 370 400 420 450 475]


##Loops Versus Vectorization

In [51]:
daily_users = [200,220,250,275]

du_np = np.array(daily_users)
np.mean(du_np)

236.25

In [3]:
import time
large_array = np.random.randint(1,100,size=10000000)

start_time = time.time()
avg = 0
for i in large_array:
  avg+=i
print(avg/10000000000)
end_time = time.time()
print("Loop time : ",end_time-start_time)


start_time_np = time.time()
print(np.mean(large_array))
end_time_np = time.time()
print("Vectorization time : ",end_time_np-start_time_np)

0.0499969978
Loop time :  1.6320726871490479
49.9969978
Vectorization time :  0.014075279235839844


##ExerciseProject 10.2 Vectorization

In [8]:
#Task 1
monthly_sales = [100,200,102,203,450,245,253,643,123,532,300,123]
discounted_sales =[]

for i in range(len(monthly_sales)):
  discounted_sales.append(monthly_sales[i]-(monthly_sales[i]*0.1))

print(discounted_sales)

#Task 2

monthly_sales = np.array([100,200,102,203,450,245,253,643,123,532,300,123])
discounted_sales = monthly_sales-(monthly_sales*0.1)
print(discounted_sales)


[90.0, 180.0, 91.8, 182.7, 405.0, 220.5, 227.7, 578.7, 110.7, 478.8, 270.0, 110.7]
[ 90.  180.   91.8 182.7 405.  220.5 227.7 578.7 110.7 478.8 270.  110.7]


##Universal Functions

In [10]:
product_prices = np.array([20,24,50,32,55])

print(np.sqrt(product_prices))

[4.47213595 4.89897949 7.07106781 5.65685425 7.41619849]


In [12]:
revenue = np.array([4000,4500,5000])
expenses = np.array([2000,1000,1500])

print(np.subtract(revenue,expenses))

[2000 3500 3500]


In [16]:
revenue = np.array([4000,4500,5000])
expenses = np.array([2000,1000,1500])

np.less_equal(expenses, 2000)


array([ True,  True,  True])

##Conditional Filtering

In [21]:
scores = np.array([70,50,30,24,60,80,90])
eligibility = np.where(scores>50,"Yes","No")
print(eligibility)

['Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes']


In [22]:
eligibility = np.where((scores>30) & (scores<70),"Yes","No")
print(eligibility)

['No' 'Yes' 'No' 'No' 'Yes' 'No' 'No']


##Reshaping Arrays


##Handling Missing Values Using NumPy

In [28]:
customer_data=np.array([100,150,np.nan,200,156])
print(customer_data)
missing_values = np.isnan(customer_data)

print("We missing",np.sum(missing_values),"value")

mean_data = np.nanmean(customer_data)

data_mean_filled = np.where(np.isnan(customer_data),mean_data,customer_data)

print(data_mean_filled)


[100. 150.  nan 200. 156.]
We missing 1 value
[100.  150.  151.5 200.  156. ]


In [31]:
customer_data=np.array([100,150,np.nan,200,156])

data_without_nan = customer_data[~np.isnan(customer_data)]
print(data_without_nan)

[100. 150. 200. 156.]
